apiVersion: v1
kind: Service
metadata:
  name: {{ include "standard-deploy.fullServiceName" . }}
  labels:
    app: {{ include "standard-deploy.fullServiceName" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.releaseName }}-{{ .Values.subDomain }}

