image:
  repository: quay.io/jetstack/cert-manager-controller-arm64
webhook:
  image:
    repository: quay.io/jetstack/cert-manager-webhook-arm64
cainjector:
  image:
    repository: quay.io/jetstack/cert-manager-cainjector-arm64
extraArgs:
  - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver-arm64:v0.7.0
