name: AWS Sample
on: push
jobs:
  list-buckets:
    runs-on: ubuntu-latest
    steps:
    - name: List S3 Buckets
      uses: actions/aws/cli@master
      with:
        args: s3 ls
        aws_access_key_id: ${{ secrets.aws_access_key_id }}
        aws_secret_access_key: ${{ secrets.aws_secret_access_key }}