name: AWS Sample
on: push
jobs:
  list-buckets:
    runs-on: ubuntu-latest
    steps:
    - name: List S3 Buckets
      uses: actions/aws/cli@master
      with:
        args: s3 ls
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}