name: Publish S3 Site
on: push
jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: sync-dev
      if: github.ref != 'master'
      uses: actions/aws/cli@master
      with:
        args: s3 sync k8s/ s3://sobota-actions-testing
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}