name: Publish to SNS Topic
on: push
jobs:
  topic:
    runs-on: ubuntu-latest
    steps:
    - name: create-topic
      uses: actions/aws/cli@master
      with:
        args: sns create-topic --name my-topic
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  print-output:
    needs: topic
    runs-on: ubuntu-latest
    steps:
      - name: list dir
        run: ls
  publish:
    needs: topic
    runs-on: ubuntu-latest
    steps:
    - name: publish-to-topic
      uses: actions/aws/cli@master
      with:
        args: sns publish --topic-arn `jq .TopicArn /github/home/topic.json --raw-output` --subject \"[$GITHUB_REPOSITORY] Code was pushed to $GITHUB_REF\" --message file://$GITHUB_EVENT_PATH"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}